import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-indie',
  imports: [CommonModule],
  templateUrl: './indie.html',
  styleUrl: './indie.css',
})
export class Indie {
public infoVideojuegos: Videojuegos[];

constructor() {
this.infoVideojuegos = [
    { id: 1,
  titulo: "Terraria",
  categoria: "Indie",
  descripcion: "Terraria es un sandbox-aventura en 2D donde excavas, luchas, exploras y construyes en un mundo que nunca es igual. Mina profundidades, descubre tesoros, derrota jefes y construye tu propio asentamiento.",
  img: "https://store.steampowered.com/app/105600/header.jpg",
  alt: "Terraria",
  precio: 9.99,
  fecha_lanzamiento: new Date("5-16-2011"),
},
{ id: 2,
  titulo: "Undertale",
  categoria: "Indie",
  descripcion: "Undertale es un RPG independiente que te permite decidir cómo tratar a tus enemigos: puedes huir, convivir o combatir. Con humor singular, múltiples finales y una historia que se ramifica con tus decisiones.",
  img: "https://store.steampowered.com/app/391540/header.jpg",
  alt: "Undertale",
  precio: 14.99,
  fecha_lanzamiento: new Date("9-15-2015"),
},
{ id: 3,
  titulo: "Celeste",
  categoria: "Indie",
  descripcion: "Celeste es un plataformas desafiante con una historia emocional de superación: ayuda a Madeline a escalar la montaña Celeste enfrentando tanto los retos del mundo como sus propias inseguridades.",
  img: "https://store.steampowered.com/app/504230/header.jpg",
  alt: "Celeste",
  precio: 19.99,
  fecha_lanzamiento: new Date("1-25-2018"),
},
{ id: 4,
  titulo: "Vampire Survivors",
  categoria: "Indie",
  descripcion: "Vampire Survivors es un roguelite minimalista donde hordas de criaturas se te echan encima: elige armas, mejora tu build, resiste lo máximo posible. Simple, adictivo y altamente rejugable.",
  img: "https://store.steampowered.com/app/1794680/header.jpg",
  alt: "Vampire Survivors",
  precio: 3.49,
  fecha_lanzamiento: new Date("10-20-2022"),
},
{ id: 5,
  titulo: "The Binding of Isaac: Rebirth",
  categoria: "Indie",
  descripcion: "The Binding of Isaac: Rebirth es un shooter-RPG roguelike donde cada partida es distinta: cientos de ítems, niveles generados, permadeath y una mezcla extraña de humor, oscuridad y desafio constante.",
  img: "https://store.steampowered.com/app/250900/header.jpg",
  alt: "The Binding of Isaac: Rebirth",
  precio: 14.99,
  fecha_lanzamiento: new Date("11-4-2014"),
},
{ id: 6,
  titulo: "Dead Cells",
  categoria: "Indie",
  descripcion: "Dead Cells es un action rogue/Metroidvania donde mueres, mejoras y vuelves a intentarlo. Combina combate fluido, niveles generados y gran variedad de armas y poderes para una experiencia indie de alto calibre.",
  img: "https://store.steampowered.com/app/588650/header.jpg",
  alt: "Dead Cells",
  precio: 24.99,
  fecha_lanzamiento: new Date("8-7-2018"),
},
{ id: 7,
  titulo: "Hades",
  categoria: "Indie",
  descripcion: "Hades mezcla mitología griega, acción rápida estilo rogue-lite y narrativa sólida: como príncipe del inframundo intentarás escapar mientras forjas relaciones con los dioses, mejoras tu equipamiento y descubres secretos.",
  img: "https://store.steampowered.com/app/1145360/header.jpg",
  alt: "Hades",
  precio: 24.99,
  fecha_lanzamiento: new Date("9-17-2020"),
},
{ id: 8,
  titulo: "Cuphead",
  categoria: "Indie",
  descripcion: "Cuphead destaca por su estilo artístico inspirado en los dibujos animados de los años 30 y sus combates contra jefes difíciles. Un run-and-gun exigente pero bellamente animado, con banda sonora de jazz.",
  img: "https://store.steampowered.com/app/268910/header.jpg",
  alt: "Cuphead",
  precio: 19.99,
  fecha_lanzamiento: new Date("9-29-2017"),
},
{ id: 9,
  titulo: "Slay the Spire",
  categoria: "Indie",
  descripcion: "Slay the Spire fusiona construcción de mazos (deck-building) y roguelike: escoge entre personajes, elige cartas, mejora tu baraja con reliquias y avanza planta por planta enfrentando enemigos. Muy rejugable y estratégico.",
  img: "https://store.steampowered.com/app/646570/header.jpg",
  alt: "Slay the Spire",
  precio: 24.99,
  fecha_lanzamiento: new Date("11-20-2017"),
},
{ id: 10,
  titulo: "Hollow Knight",
  categoria: "Indie",
  descripcion: "Hollow Knight es un Metroidvania atmosférico, desafiante y bellamente dibujado a mano. Explora un mundo interconectado de cavernas y ruinas, descubre secretos, mejora tu personaje y enfréntate a jefes memorables.",
  img: "https://store.steampowered.com/app/367520/header.jpg",
  alt: "Hollow Knight",
  precio: 14.99,
  fecha_lanzamiento: new Date("2-24-2017"),
},
{ id: 11,
  titulo: "Among Us",
  categoria: "Indie",
  descripcion: "Among Us es un juego de deducción social en línea: colabora o traiciona con tus amigos para completar tareas en una nave espacial… o conviértete en el impostor y sabotea la misión. Fue un fenómeno indie mundial.",
  img: "https://store.steampowered.com/app/945360/header.jpg",
  alt: "Among Us",
  precio: 4.99,
  fecha_lanzamiento: new Date("11-16-2018"),
},
{ id: 12,
  titulo: "Brotato",
  categoria: "Indie",
  descripcion: "Brotato es un roguelite shooter top-down accesible donde controlas un personaje que lucha hordas mientras mejoras su build. Muy popular en Steam gracias a su diversión rápida, estilo sencillo y rejugabilidad alta. :contentReference[oaicite:1]{index=1}",
  img: "https://store.steampowered.com/app/2004230/header.jpg",
  alt: "Brotato",
  precio: 5.00,
  fecha_lanzamiento: new Date("6-23-2023"),
},

  ]

}
}
