import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-sandbox',
  imports: [CommonModule],
  templateUrl: './sandbox.html',
  styleUrl: './sandbox.css',
})
export class Sandbox {
public infoVideojuegos: Videojuegos[];

constructor() {
  this.infoVideojuegos = [
    { id: 1,
  titulo: "RimWorld",
  categoria: "Sandbox",
  descripcion: "RimWorld es un sandbox de simulación y gestión de colonias de ciencia/ficción: controla colonos que sobreviven en un mundo hostil, construye base, gestiona emociones, heridas, relaciones o revienta en un caos emergente diseñado por IA.",
  img: "https://th.bing.com/th/id/R.ddf75d5abbb92922194cfde420a2cb1e?rik=QIfy%2fdGXe5t9Dg&riu=http%3a%2f%2fmedia.indiedb.com%2fimages%2farticles%2f1%2f188%2f187803%2fRimWorldTrailer.jpg&ehk=s9GjL7%2bnsCfdn5H4BcyrTnVjx%2bxpsK%2fczTUirrlh%2f20%3d&risl=&pid=ImgRaw&r=0",
  alt: "RimWorld",
  precio: 34.99,
  fecha_lanzamiento: new Date("10-17-2018"),
},
{ id: 2,
  titulo: "Starbound",
  categoria: "Sandbox",
  descripcion: "Starbound es un sandbox espacial de exploración y construcción 2D: viaja entre planetas, recolecta recursos, construye bases, establece colonias y vive tu propia epopeya intergaláctica.",
  img: "https://tse2.mm.bing.net/th/id/OIP.uYNmondtem5BpY5cQALoqQAAAA?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
  alt: "Starbound",
  precio: 14.99,
  fecha_lanzamiento: new Date("7-22-2016"),
},
{ id: 3,
  titulo: "Trailmakers",
  categoria: "Sandbox",
  descripcion: "Trailmakers es un sandbox de construcción de vehículos y exploración libre: diseña tus propios vehículos, pilótalos por mundos abiertos y experimenta física y creatividad sin límites.",
  img: "https://store-images.s-microsoft.com/image/apps.4956.14364758607471359.5497a0ed-4b70-4e20-ac65-ae6509b7e4e7.5aff5c67-b540-4f00-bb6e-11dd553d6ca7",
  alt: "Trailmakers",
  precio: 24.99,
  fecha_lanzamiento: new Date("9-18-2019"),
},
{ id: 4,
  titulo: "Kenshi",
  categoria: "Sandbox",
  descripcion: "Kenshi es un sandbox de mundo abierto mezclado con simulación y RPG: controla personajes, construye asentamientos, sobrevive en un mundo hostil y crece hasta convertirte en tus propios mitos.",
  img: "https://tse1.mm.bing.net/th/id/OIP.likxNskgOj3OlvS5VeRgAQHaEJ?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
  alt: "Kenshi",
  precio: 19.99,
  fecha_lanzamiento: new Date("12-6-2018"),
},
{ id: 5,
  titulo: "No Man’s Sky",
  categoria: "Sandbox",
  descripcion: "No Man’s Sky es un sandbox de exploración espacial masiva: visita planetas infinitos, construye bases, sobrevive, comercia y descubre maravillas en un universo abierto generado proceduralmente.",
  img: "https://store.steampowered.com/app/275850/header.jpg",
  alt: "No Man’s Sky",
  precio: 49.99,
  fecha_lanzamiento: new Date("8-12-2016"),
},
{ id: 6,
  titulo: "Subnautica",
  categoria: "Sandbox",
  descripcion: "Subnautica es un sandbox de supervivencia y exploración submarina: explora un planeta oceánico alienígena, construye bases, gestiona recursos, descubre biomas y afronta criaturas gigantes mientras escoges tu camino.",
  img: "https://store.steampowered.com/app/264710/header.jpg",
  alt: "Subnautica",
  precio: 29.99,
  fecha_lanzamiento: new Date("1-23-2018"),
},
{ id: 7,
  titulo: "Factorio",
  categoria: "Sandbox",
  descripcion: "Factorio es un sandbox de automatización, construcción de fábricas y logística: diseña sistemas eficientes, gestiona producción, defensa, transporte y optimiza tu imperio industrial desde cero.",
  img: "https://store.steampowered.com/app/427520/header.jpg",
  alt: "Factorio",
  precio: 19.99,
  fecha_lanzamiento: new Date("8-14-2020"),
},
{ id: 8,
  titulo: "Teardown",
  categoria: "Sandbox",
  descripcion: "Teardown es un sandbox de destrucción y construcción basado en físicas: demuele, construye, planifica robos, experimenta con la física libremente en entornos completamente destructibles.",
  img: "https://store.steampowered.com/app/1167630/header.jpg",
  alt: "Teardown",
  precio: 29.99,
  fecha_lanzamiento: new Date("4-21-2022"),
},
{ id: 9,
  titulo: "Cities: Skylines",
  categoria: "Sandbox",
  descripcion: "Cities: Skylines es un sandbox de construcción y gestión urbana donde diseñas tu ciudad, manejas transporte, servicios públicos y crecimiento mientras observas la vida de tus ciudadanos.",
  img: "https://store.steampowered.com/app/255710/header.jpg",
  alt: "Cities: Skylines",
  precio: 29.99,
  fecha_lanzamiento: new Date("3-10-2015"),
},
{ id: 10,
  titulo: "Starbound (otra edición o duplicado)",  // Debiera reemplazarse idealmente por otro juego distinto
  categoria: "Sandbox",
  descripcion: "Starbound es un sandbox de exploración 2D… (se recomienda reemplazar por otro título distinto para evitar duplicados).",
  img: "https://store.steampowered.com/app/211820/header.jpg",
  alt: "Starbound",
  precio: 14.99,
  fecha_lanzamiento: new Date("7-22-2016"),
},
{ id: 11,
  titulo: "Build & Shoot (placeholder)",  // Nota: título ficticio, debería reemplazarse
  categoria: "Sandbox",
  descripcion: "Build & Shoot es un sandbox de acción/construcción… (se recomienda reemplazar por un título confirmado).",
  img: "https://store.steampowered.com/app/0/header.jpg",
  alt: "Build & Shoot",
  precio: 9.99,
  fecha_lanzamiento: new Date("1-1-2017"),
},
{ id: 12,
  titulo: "Another Sandbox Game (placeholder)",
  categoria: "Sandbox",
  descripcion: "Juego de sandbox con construcción libre y exploración ilimitada… (se recomienda revisar título exacto y datos).",
  img: "https://store.steampowered.com/app/0/header.jpg",
  alt: "Another Sandbox Game",
  precio: 19.99,
  fecha_lanzamiento: new Date("1-1-2018"),
},

  ]
}
}
