import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-puzle',
  imports: [CommonModule],
  templateUrl: './puzle.html',
  styleUrl: './puzle.css',
})
export class Puzle {
public infoVideojuegos: Videojuegos[];

constructor() {
  this.infoVideojuegos = [
    { id: 1,
  titulo: "Portal 2",
  categoria: "Puzle",
  descripcion: "En Portal 2 usarás la pistola de portales para atravesar cámaras de pruebas ideadas por la IA GLaDOS. Ingenio, humor oscuro y mecánicas de teletransporte redefinen el género de puzzles en primera persona.",
  img: "https://store.steampowered.com/app/620/header.jpg",
  alt: "Portal 2",
  precio: 19.99,
  fecha_lanzamiento: new Date("4‑19‑2011"),
},
{ id: 2,
  titulo: "The Talos Principle",
  categoria: "Puzle",
  descripcion: "The Talos Principle es un juego de puzles filosófico en primera persona: explora ruinas antiguas, resuelve acertijos que involucran rayos láser, bloques y tiempo, mientras reflexionas sobre la conciencia y lo que significa ser humano. :contentReference[oaicite:0]{index=0}",
  img: "https://store.steampowered.com/app/257510/header.jpg",
  alt: "The Talos Principle",
  precio: 29.99,
  fecha_lanzamiento: new Date("12‑11‑2014"),
},
{ id: 3,
  titulo: "Baba Is You",
  categoria: "Puzle",
  descripcion: "Baba Is You es un juego ingenioso en el que las reglas mismas del nivel son bloques que puedes mover y cambiar: conviértete en roca, cambia la meta o el propio objetivo para resolver cada nivel. :contentReference[oaicite:1]{index=1}",
  img: "https://store.steampowered.com/app/736260/header.jpg",
  alt: "Baba Is You",
  precio: 14.99,
  fecha_lanzamiento: new Date("3‑13‑2019"),
},
{ id: 4,
  titulo: "Antichamber",
  categoria: "Puzle",
  descripcion: "Antichamber te sumerge en un espacio laberíntico imposible donde la geometría desafía la lógica: pasillos que cambian, objetos que se comportan sin seguir la física habitual y acertijos que rompen tus expectativas. :contentReference[oaicite:2]{index=2}",
  img: "https://store.steampowered.com/app/219890/header.jpg",
  alt: "Antichamber",
  precio: 19.99,
  fecha_lanzamiento: new Date("1‑31‑2013"),
},
{ id: 5,
  titulo: "The Witness",
  categoria: "Puzle",
  descripcion: "The Witness te lleva a una isla abierta llena de paneles de línea, símbolos y mecánicas que evolucionan a lo largo del juego. Explora libremente, observa el entorno, aprende las reglas y resuélvelas hasta comprender el todo.",
  img: "https://store.steampowered.com/app/210970/header.jpg",
  alt: "The Witness",
  precio: 39.99,
  fecha_lanzamiento: new Date("1‑26‑2016"),
},
{ id: 6,
  titulo: "Human Fall Flat",
  categoria: "Puzle",
  descripcion: "Human Fall Flat es un juego de puzles físicos multijugador con un protagonista de plastilina que resuelve desafíos de equilibrio, plataformas y cooperación. Ideal para jugar con amigos y experimentar. ",
  img: "https://store.steampowered.com/app/477160/header.jpg",
  alt: "Human Fall Flat",
  precio: 14.99,
  fecha_lanzamiento: new Date("7‑22‑2016"),
},
{ id: 7,
  titulo: "Limbo",
  categoria: "Puzle",
  descripcion: "Limbo es un juego de plataformas y puzle atmosférico: salta, resuelve mecanismos y evita peligros en un mundo monocromo y sin apenas texto, con diseño artístico minimalista pero intenso.",
  img: "https://store.steampowered.com/app/48000/header.jpg",
  alt: "Limbo",
  precio: 9.99,
  fecha_lanzamiento: new Date("7‑21‑2010"),
},
{ id: 8,
  titulo: "Inside",
  categoria: "Puzle",
  descripcion: "Inside, de los creadores de Limbo, combina puzzles ambientales, plataformas y narrativa potente. Un niño en un mundo opresivo escapa y descubre secretos inquietantes mientras resuelve rompecabezas ingeniosos.",
  img: "https://store.steampowered.com/app/304430/header.jpg",
  alt: "Inside",
  precio: 19.99,
  fecha_lanzamiento: new Date("6‑29‑2016"),
},
{ id: 9,
  titulo: "Stephen’s Sausage Roll",
  categoria: "Puzle",
  descripcion: "Stephen’s Sausage Roll es un puzle retador donde empujas salchichas sobre placas de parrilla, quemarlas incorrectamente es fallar. Minimalismo de reglas, máxima profundidad: considerado uno de los puzles más difíciles pero brillantes.",
  img: "https://store.steampowered.com/app/1281470/header.jpg",
  alt: "Stephen’s Sausage Roll",
  precio: 24.99,
  fecha_lanzamiento: new Date("5‑27‑2021"),
},
{ id: 10,
  titulo: "Q.U.B.E. 2",
  categoria: "Puzle",
  descripcion: "Q.U.B.E. 2 es un juego de rompecabezas en primera persona donde manipulas bloques, resortes y mecanismos en habitaciones de diseño limpio, inspirado por Portal, con estética moderna y retos bien calibrados. :contentReference[oaicite:3]{index=3}",
  img: "https://store.steampowered.com/app/406670/header.jpg",
  alt: "Q.U.B.E. 2",
  precio: 19.99,
  fecha_lanzamiento: new Date("3‑15‑2018"),
},
{ id: 11,
  titulo: "Slayaway Camp 2",
  categoria: "Puzle",
  descripcion: "Slayaway Camp 2 es un juego de puzles‑movimiento ambientado en una estética de terror ochentero: mueve al asesino para resolver laberintos, evitar trampas y eliminar campistas. Una opción divertida que mezcla humor negro y rompecabezas. :contentReference[oaicite:4]{index=4}",
  img: "https://store.steampowered.com/app/1609600/header.jpg",
  alt: "Slayaway Camp 2",
  precio: 12.79,
  fecha_lanzamiento: new Date("10‑28‑2022"),
},
{ id: 12,
  titulo: "A Monster’s Expedition",
  categoria: "Puzle",
  descripcion: "A Monster’s Expedition es un juego tranquilo de exploración y puzles: rodar, empujar y mover tu esqueleto‑científico vestido de traje por islas conectadas para descubrir secretos antiguos. Ideal para jugar sin presión. ",
  img: "https://store.steampowered.com/app/1289250/header.jpg",
  alt: "A Monster’s Expedition",
  precio: 19.99,
  fecha_lanzamiento: new Date("10‑27‑2021"),
},

  ]
}
}
