import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-rpg',
  imports: [CommonModule],
  templateUrl: './rpg.html',
  styleUrl: './rpg.css',
})
export class Rpg {
public infoVideojuegos: Videojuegos[];

constructor() {
  this.infoVideojuegos = [
    { id: 1,
  titulo: "Baldur’s Gate 3",
  categoria: "RPG",
  descripcion: "Baldur’s Gate 3 es un RPG basado en Dungeons & Dragons con profunda narrativa, combate táctico por turnos y libertad para definir el destino de tu grupo de héroes. ",
  img: "https://store.steampowered.com/app/1086940/header.jpg",
  alt: "Baldur’s Gate 3",
  precio: 59.99,
  fecha_lanzamiento: new Date("8-3-2023"),
},
{ id: 2,
  titulo: "Persona 5 Royal",
  categoria: "RPG",
  descripcion: "Persona 5 Royal es la versión ampliada del JRPG donde lideras a los Phantom Thieves, exploras mazmorras, gestionas relaciones y vives una historia estilizada ambientada en Tokio. ",
  img: "https://store.steampowered.com/app/1687950/header.jpg",
  alt: "Persona 5 Royal",
  precio: 59.99,
  fecha_lanzamiento: new Date("10-20-2022"),
},
{ id: 3,
  titulo: "The Witcher 3: Wild Hunt - Complete Edition",
  categoria: "RPG",
  descripcion: "The Witcher 3: Wild Hunt te pone en el papel del brujo Geralt de Rivia en un mundo abierto lleno de monstruos, intrigas y decisiones que realmente importan. Incluye todos los DLCs. ",
  img: "https://store.steampowered.com/app/292030/header.jpg",
  alt: "The Witcher 3: Wild Hunt - Complete Edition",
  precio: 39.99,
  fecha_lanzamiento: new Date("5-18-2015"),
},
{ id: 4,
  titulo: "Cyberpunk 2077",
  categoria: "RPG",
  descripcion: "Cyberpunk 2077 te lleva a Night City, una ciudad futurista donde la tecnología y el crimen se entrelazan. Crea tu protagonista, lleva misiones, explora libremente y define tu historia. ",
  img: "https://store.steampowered.com/app/1091500/header.jpg",
  alt: "Cyberpunk 2077",
  precio: 59.99,
  fecha_lanzamiento: new Date("12-9-2020"),
},
{ id: 5,
  titulo: "Fallout 4 - Game of the Year Edition",
  categoria: "RPG",
  descripcion: "Fallout 4 te sitúa en un mundo post-apocalíptico donde decides tu rol tras salir del Refugio 111. Construye, explora el Yermo, elige alianzas o enfrenta facciones mutantes. Incluye todos los DLC. ",
  img: "https://store.steampowered.com/app/377160/header.jpg",
  alt: "Fallout 4 - Game of the Year Edition",
  precio: 29.99,
  fecha_lanzamiento: new Date("11-10-2015"),
},
{ id: 6,
  titulo: "Divinity Original Sin 2 - Definitive Edition",
  categoria: "RPG",
  descripcion: "Divinity Original Sin 2 - Definitive Edition ofrece combate táctico profundo, cooperativo exigente, personajes variados y una historia donde tus decisiones cambian el mundo. ",
  img: "https://store.steampowered.com/app/435150/header.jpg",
  alt: "Divinity Original Sin 2 - Definitive Edition",
  precio: 49.99,
  fecha_lanzamiento: new Date("9-14-2017"),
},
{ id: 7,
  titulo: "Monster Hunter World",
  categoria: "RPG",
  descripcion: "Monster Hunter World es un action/RPG cooperativo donde cazas monstruos gigantes, dominas armas exóticas y exploras ecosistemas vivos solo o con amigos. ",
  img: "https://store.steampowered.com/app/582010/header.jpg",
  alt: "Monster Hunter World",
  precio: 39.99,
  fecha_lanzamiento: new Date("8-9-2018"),
},
{ id: 8,
  titulo: "The Outer Worlds - Epic Edition",
  categoria: "RPG",
  descripcion: "The Outer Worlds - Epic Edition es un RPG de ciencia ficción donde despiertas de criogenia, exploras planetas extraños, completas misiones corporativas y tus elecciones realmente importan. ",
  img: "https://store.steampowered.com/app/859430/header.jpg",
  alt: "The Outer Worlds - Epic Edition",
  precio: 39.99,
  fecha_lanzamiento: new Date("10-25-2019"),
},
{ id: 9,
  titulo: "Tales of Arise",
  categoria: "RPG",
  descripcion: "Tales of Arise es un JRPG moderno con combates dinámicos en 3D, una historia emotiva sobre superar la opresión y personajes memorables. ",
  img: "https://store.steampowered.com/app/1296650/header.jpg",
  alt: "Tales of Arise",
  precio: 59.99,
  fecha_lanzamiento: new Date("9-9-2021"),
},
{ id: 10,
  titulo: "Kingdom Come: Deliverance",
  categoria: "RPG",
  descripcion: "Kingdom Come: Deliverance es un RPG de acción histórica ambientado en la Bohemia medieval: combate realista, historia seria y mundo abierto verosímil. ",
  img: "https://store.steampowered.com/app/379430/header.jpg",
  alt: "Kingdom Come: Deliverance",
  precio: 49.99,
  fecha_lanzamiento: new Date("2-13-2018"),
},
{ id: 11,
  titulo: "Diablo IV",
  categoria: "RPG",
  descripcion: "Diablo IV es un RPG de acción oscuro donde seleccionas entre clases, exploras un mundo abierto interconectado y luchas contra hordas de demonios tanto solo como en modo cooperativo. ",
  img: "https://store.steampowered.com/app/1716740/header.jpg",
  alt: "Diablo IV",
  precio: 59.99,
  fecha_lanzamiento: new Date("6-6-2023"),
},
{ id: 12,
  titulo: "Persona 5 Strikers (For the PG) (Nota: edición estándar)",
  categoria: "RPG",
  descripcion: "Persona 5 Strikers es un híbrido de JRPG y acción con personajes del universo Persona: lucha, historia y partes de exploración para los fans de la serie Persona. ",
  img: "https://store.steampowered.com/app/1657370/header.jpg",
  alt: "Persona 5 Strikers",
  precio: 49.99,
  fecha_lanzamiento: new Date("2-23-2023"),
},

  ]
}
}
