import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-rpg',
  imports: [CommonModule],
  templateUrl: './rpg.html',
  styleUrl: './rpg.css',
})
export class Rpg {
public infoVideojuegos: Videojuegos[];

constructor() {
  this.infoVideojuegos = [
    { id: 1,
  titulo: "Baldur’s Gate 3",
  categoria: "RPG",
  descripcion: "Baldur’s Gate 3 es un RPG basado en Dungeons & Dragons con profunda narrativa, combate táctico por turnos y libertad para definir el destino de tu grupo de héroes. ",
  img: "https://cdn.wccftech.com/wp-content/uploads/2023/08/Baldurs-Gate-3-header-scaled.jpg",
  alt: "Baldur’s Gate 3",
  precio: 59.99,
  fecha_lanzamiento: new Date("8-3-2023"),
},
{ id: 2,
  titulo: "Persona 5 Royal",
  categoria: "RPG",
  descripcion: "Persona 5 Royal es la versión ampliada del JRPG donde lideras a los Phantom Thieves, exploras mazmorras, gestionas relaciones y vives una historia estilizada ambientada en Tokio. ",
  img: "https://tse4.mm.bing.net/th/id/OIP.olrrLpN1NqUCBQrRljPqQQHaD5?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
  alt: "Persona 5 Royal",
  precio: 59.99,
  fecha_lanzamiento: new Date("10-20-2022"),
},
{ id: 3,
  titulo: "The Witcher 3: Wild Hunt - Complete Edition",
  categoria: "RPG",
  descripcion: "The Witcher 3: Wild Hunt te pone en el papel del brujo Geralt de Rivia en un mundo abierto lleno de monstruos, intrigas y decisiones que realmente importan. Incluye todos los DLCs. ",
  img: "https://tse4.mm.bing.net/th/id/OIP.4U-PWSBDpOGhPnSwsLwKgQHaHa?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
  alt: "The Witcher 3: Wild Hunt - Complete Edition",
  precio: 39.99,
  fecha_lanzamiento: new Date("5-18-2015"),
},
{ id: 4,
  titulo: "Cyberpunk 2077",
  categoria: "RPG",
  descripcion: "Cyberpunk 2077 te lleva a Night City, una ciudad futurista donde la tecnología y el crimen se entrelazan. Crea tu protagonista, lleva misiones, explora libremente y define tu historia. ",
  img: "https://store.steampowered.com/app/1091500/header.jpg",
  alt: "Cyberpunk 2077",
  precio: 59.99,
  fecha_lanzamiento: new Date("12-9-2020"),
},
{ id: 5,
  titulo: "Fallout 4 - Game of the Year Edition",
  categoria: "RPG",
  descripcion: "Fallout 4 te sitúa en un mundo post-apocalíptico donde decides tu rol tras salir del Refugio 111. Construye, explora el Yermo, elige alianzas o enfrenta facciones mutantes. Incluye todos los DLC. ",
  img: "https://tse2.mm.bing.net/th/id/OIP.xVWuF3dGqhTULjSqH94W5wHaJ4?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
  alt: "Fallout 4 - Game of the Year Edition",
  precio: 29.99,
  fecha_lanzamiento: new Date("11-10-2015"),
},
{ id: 6,
  titulo: "Divinity Original Sin 2 - Definitive Edition",
  categoria: "RPG",
  descripcion: "Divinity Original Sin 2 - Definitive Edition ofrece combate táctico profundo, cooperativo exigente, personajes variados y una historia donde tus decisiones cambian el mundo. ",
  img: "https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/ncom/pt_BR/games/switch/d/divinity-original-sin-2-definitive-edition-switch/hero",
  alt: "Divinity Original Sin 2 - Definitive Edition",
  precio: 49.99,
  fecha_lanzamiento: new Date("9-14-2017"),
},
{ id: 7,
  titulo: "Monster Hunter World",
  categoria: "RPG",
  descripcion: "Monster Hunter World es un action/RPG cooperativo donde cazas monstruos gigantes, dominas armas exóticas y exploras ecosistemas vivos solo o con amigos. ",
  img: "https://image.api.playstation.com/vulcan/img/rnd/202010/0106/IyY3JSzHNCVoh7FultMPaE8F.jpg",
  alt: "Monster Hunter World",
  precio: 39.99,
  fecha_lanzamiento: new Date("8-9-2018"),
},
{ id: 8,
  titulo: "The Outer Worlds - Epic Edition",
  categoria: "RPG",
  descripcion: "The Outer Worlds - Epic Edition es un RPG de ciencia ficción donde despiertas de criogenia, exploras planetas extraños, completas misiones corporativas y tus elecciones realmente importan. ",
  img: "https://tse3.mm.bing.net/th/id/OIP.EsTikyC2Adf_kPT3tTMfoAHaEo?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
  alt: "The Outer Worlds - Epic Edition",
  precio: 39.99,
  fecha_lanzamiento: new Date("10-25-2019"),
},
{ id: 9,
  titulo: "Tales of Arise",
  categoria: "RPG",
  descripcion: "Tales of Arise es un JRPG moderno con combates dinámicos en 3D, una historia emotiva sobre superar la opresión y personajes memorables. ",
  img: "https://th.bing.com/th/id/R.5761fab18d03bd1adb253848604e04bb?rik=obmJcToihCq%2fkw&pid=ImgRaw&r=0",
  alt: "Tales of Arise",
  precio: 59.99,
  fecha_lanzamiento: new Date("9-9-2021"),
},
{ id: 10,
  titulo: "Kingdom Come: Deliverance",
  categoria: "RPG",
  descripcion: "Kingdom Come: Deliverance es un RPG de acción histórica ambientado en la Bohemia medieval: combate realista, historia seria y mundo abierto verosímil. ",
  img: "https://cdn.alza.cz/Foto/or/articles/21610/img/kingdom-come-deliverance-thumbnail-main.jpg",
  alt: "Kingdom Come: Deliverance",
  precio: 49.99,
  fecha_lanzamiento: new Date("2-13-2018"),
},
{ id: 11,
  titulo: "Diablo IV",
  categoria: "RPG",
  descripcion: "Diablo IV es un RPG de acción oscuro donde seleccionas entre clases, exploras un mundo abierto interconectado y luchas contra hordas de demonios tanto solo como en modo cooperativo. ",
  img: "https://tse2.mm.bing.net/th/id/OIP.xHxHaIFzsNU40aLJFwRetQHaD4?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
  alt: "Diablo IV",
  precio: 59.99,
  fecha_lanzamiento: new Date("6-6-2023"),
},
{ id: 12,
  titulo: "Persona 5 Strikers",
  categoria: "RPG",
  descripcion: "Persona 5 Strikers es un híbrido de JRPG y acción con personajes del universo Persona: lucha, historia y partes de exploración para los fans de la serie Persona. ",
  img: "https://tse1.mm.bing.net/th/id/OIP.WRXkOiblfcl9PXRRCztLUwHaEK?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
  alt: "Persona 5 Strikers",
  precio: 49.99,
  fecha_lanzamiento: new Date("2-23-2023"),
},

  ]
}
}
