import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-casual',
  imports: [CommonModule],
  templateUrl: './casual.html',
  styleUrl: './casual.css',
})
export class Casual {
public infoVideojuegos: Videojuegos[];

constructor() {
  this.infoVideojuegos = [
    {
    id: 1,
    titulo: "RV There Yet?",
    categoria: "Casual",
    descripcion: "Una aventura cooperativa que consiste en conducir una autocaravana de vuelta a casa.",
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3949040/cae24b4ed7f4531be51f0d63f785b7d253f92dc3/header.jpg?t=1761681404",
    alt: "RV There Yet?",
    precio: 4.99,
    fecha_lanzamiento: new Date("10-21-2025"),
    },

    {
    id: 2,
    titulo: "Bloons TD 6",
    categoria: "Casual",
    descripcion: "El exitoso juego de defensa de torres",
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/960090/header.jpg?t=1761619015",
    alt: "Bloons TD 6",
    precio: 7.79,
    fecha_lanzamiento: new Date("10-17-2018"),
    },

    {
    id: 3,
    titulo: "Balatro",
    categoria: "Carreras",
    descripcion: "El roguelike de póker. Balatro es un hipnótico y genial constructor de mazos donde podrás jugar manos ilegales de póker, descubrir comodines que alterarán tus partidas y activar combos impresionantes que dispararán tu adrenalina.",
    img: "https://tse4.mm.bing.net/th/id/OIP.kR0OemhrtQm7amxNSG7aBwHaEK?w=1024&h=576&rs=1&pid=ImgDetMain&o=7&rm=3",
    alt: "Balagod",
    precio: 7.99,
    fecha_lanzamiento: new Date("2-20-2024"),
    },

    {
    id: 4,
    titulo: "Stardew Valley",
    categoria: "Casual",
    descripcion: "Acabas de heredar la vieja parcela agrícola de tu abuelo de Stardew Valley. Decides partir hacia una nueva vida con unas herramientas usadas y algunas monedas. ¿Te ves capaz de vivir de la tierra y convertir estos campos descuidados en un hogar próspero?",
    img: "https://th.bing.com/th/id/R.97e349756e6b53e968ae22da42f386de?rik=0b%2bdh3ba7HxJgg&pid=ImgRaw&r=0",
    alt: "Stardew Valley",
    precio: 4.99,
    fecha_lanzamiento: new Date("2-26-2016"),
    },

    { id: 5,
  titulo: "Escape Simulator 2",
  categoria: "Casual",
  descripcion: "Secuela del juego de escape room más vendido, trae una variante nueva a los acertijos en primera persona con una variedad de salas para explorar solo o con amigos. Resuelve acertijos intrincados, descubre secretos ocultos o elabora tus propias escape rooms con Room Editor 2.0",  
  img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2879840/f1f548311fadd53263adca4647e380eaa75588c6/header.jpg?t=1761724381",  
  alt: "Escape Simulator 2",
  precio: 8.09,
  fecha_lanzamiento: new Date("10-27-2025"),
},
{ id: 6,
  titulo: "People Playground",
  categoria: "Casual",
  descripcion: "People Playground es un sandbox donde experimentas libremente con ragdolls, física, objetos y escenarios creados por la comunidad. Ideal para partidas informales y creatividad sin ataduras.",  
  img: "https://store.steampowered.com/app/1118200/header.jpg",  
  alt: "People Playground",
  precio: 9.99,
  fecha_lanzamiento: new Date("7-23-2019"),
},
{ id: 7,
  titulo: "Vampire Survivors",
  categoria: "Casual",
  descripcion: "En Vampire Survivors sobrevives oleadas de criaturas nocturnas con estilo roguelite y controles simples, buscando la mejor combinación de armas y mejoras para aguantar lo máximo posible.",  
  img: "https://store.steampowered.com/app/1794680/header.jpg",  
  alt: "Vampire Survivors",
  precio: 3.49,
  fecha_lanzamiento: new Date("10-20-2022"),
},
{ id: 8,
  titulo: "PowerWash Simulator",
  categoria: "Casual",
  descripcion: "PowerWash Simulator te permite limpiar con hidrolavadora diversos escenarios relajantes y satisfactorios. Perfecto para jugar sin estrés y ver el cambio visual de la limpieza.",  
  img: "https://store.steampowered.com/app/1298650/header.jpg",  
  alt: "PowerWash Simulator",
  precio: 24.99,
  fecha_lanzamiento: new Date("7-14-2022"),
},
{ id: 9,
  titulo: "ISLANDERS",
  categoria: "Casual",
  descripcion: "ISLANDERS es un juego minimalista de construcción de ciudades en islas generadas, con gráficos de bajo polígono, música tranquila y enfoque relajado para crear tu propio entorno sin prisas.",  
  img: "https://store.steampowered.com/app/933110/header.jpg",  
  alt: "ISLANDERS",
  precio: 4.99,
  fecha_lanzamiento: new Date("4-04-2019"),
},
{ id: 10,
  titulo: "Mini Metro",
  categoria: "Casual",
  descripcion: "Mini Metro te reta a diseñar mapas de metro eficientes mientras la ciudad crece. Atractivo para sesiones breves o relajadas, con estética simple y diseño ingenioso.",  
  img: "https://store.steampowered.com/app/287980/header.jpg",  
  alt: "Mini Metro",
  precio: 9.99,
  fecha_lanzamiento: new Date("9-30-2015"),
},
{ id: 11,
  titulo: "Shanshui Haven",
  categoria: "Casual",
  descripcion: "Shanshui Haven combina construcción de ciudad con arte de paisaje oriental, permitiéndote crear entornos tranquilos, armoniosos y bellamente estilizados sin presión de juego agresivo.",  
  img: "https://store.steampowered.com/app/2653480/header.jpg",  
  alt: "Shanshui Haven",
  precio: 7.99,
  fecha_lanzamiento: new Date("7-23-2024"),
},
{ id: 12,
  titulo: "Brotato",
  categoria: "Casual",
  descripcion: "Brotato es un roguelite de acción accesible donde controlas un personaje que pelea hordas mientras mejoras su build. Muy popular por su combinación de diversión rápida y estilo visual sencillo.",  
  img: "https://store.steampowered.com/app/2004230/header.jpg",  
  alt: "Brotato",
  precio: 5.00,
  fecha_lanzamiento: new Date("6-23-2023"),
},

  ]
}
}
