import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-estrategia',
  imports: [CommonModule],
  templateUrl: './estrategia.html',
  styleUrl: './estrategia.css',
})

export class Estrategia {
public infoVideojuegos: Videojuegos[];

constructor() {
this.infoVideojuegos = [
    {
    id: 1,
    titulo: "Crusader Kings III",
    categoria: "Estrategia",
    descripcion: "Ama, lucha, planea y reclama la grandeza. Determina el legado de tu casa nobiliaria en la gran estrategia en expansión de Crusader Kings III. La muerte solo es el comienzo mientras lideras el linaje de tu dinastía en esta completa simulación realista de la Edad Media.",
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1158310/cd1f9447a79cb6f09253145f1ebc6eb9ec08bd2e/header_alt_assets_11_spanish.jpg?t=1762165597",
    alt: "Crusader Kings III",
    precio: 44.99,
    fecha_lanzamiento: new Date("9-1-2024"),
    },

    {
    id: 2,
    titulo: "Hearts of Iron IV",
    categoria: "Estrategia",
    descripcion: "¡Tenemos la victoria al alcance de la mano! Tu capacidad para liderar tu nación es tu arma principal. En el juego de estrategia Hearts of Iron IV podrás ponerte el mando de cualquier nación de la II Guerra Mundial, el conflicto más fascinante de la historia mundial.",
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/394360/67bbd0057627fc2244793bcdd09260c2539499cf/header.jpg?t=1762197878",
    alt: "Hearts of Iron IV",
    precio: 29.99,
    fecha_lanzamiento: new Date("6-6-2016"),
    },

    {
    id: 3,
    titulo: "Sid Meier’s Civilization® VI",
    categoria: "Estrategia",
    descripcion: "Expande tu imperio, haz avanzar tu cultura y enfréntate a los mejores líderes de la historia. ¿Podrá tu civilización superar la prueba del tiempo?",
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/289070/header.jpg?t=1740607040",
    alt: "Sid Meier’s Civilization® VI",
    precio: 79.99,
    fecha_lanzamiento: new Date("10-21-2016"),
    },

    {
    id: 4,
    titulo: "Age of Empires IV: Anniversary Edition",
    categoria: "Estrategia",
    descripcion: "Para celebrar su primer año cautivando a millones de jugadores en todo el mundo, la galardonada y exitosa franquicia de estrategia continúa con Age of Empires IV: Edición Aniversario, sumergiéndote en las épicas batallas históricas que cambiaron el mundo.",
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1466860/header.jpg?t=1762295217",
    alt: "Age of Empires IV: Anniversary Edition",
    precio: 19.99,
    fecha_lanzamiento: new Date("10-28-2021"),
    },

    { id: 5,
  titulo: "Stellaris",
  categoria: "Estrategia",
  descripcion: "Explora el universo en Stellaris: crea un imperio interestelar, descubre nuevas especies, negocia, conquista o coopera. Un grand strategy de ciencia ficción con enormes posibilidades y rejugabilidad.",
  img: "https://store.steampowered.com/app/281990/header.jpg",
  alt: "Stellaris",
  precio: 39.99,
  fecha_lanzamiento: new Date("5-09-2016"),
},
{ id: 6,
  titulo: "Total War: WARHAMMER III",
  categoria: "Estrategia",
  descripcion: "Total War: WARHAMMER III combina estrategia por turnos y combates en tiempo real en el universo Warhammer. Dirige ejércitos colosales, conquista territorios y domina el mundo fantástico del Caos.",
  img: "https://store.steampowered.com/app/1142710/header.jpg",
  alt: "Total War: WARHAMMER III",
  precio: 59.99,
  fecha_lanzamiento: new Date("2-16-2022"),
},
{ id: 7,
  titulo: "Anno 1800",
  categoria: "Estrategia",
  descripcion: "En Anno 1800 liderarás la era industrial: construye ciudades, gestiona logística y comercio, colonias y compite económicamente con otras potencias. Un juego estratégico de construcción y gestión.",
  img: "https://store.steampowered.com/app/877750/header.jpg",
  alt: "Anno 1800",
  precio: 59.99,
  fecha_lanzamiento: new Date("4-16-2019"),
},
{ id: 8,
  titulo: "Cities: Skylines",
  categoria: "Estrategia",
  descripcion: "Diseña, construye y gestiona tu propia ciudad en Cities: Skylines. Controla transporte, servicios, presupuesto y expansión urbana mientras haces feliz (o no) a tus ciudadanos.",
  img: "https://store.steampowered.com/app/255710/header.jpg",
  alt: "Cities: Skylines",
  precio: 29.99,
  fecha_lanzamiento: new Date("3-10-2015"),
},
{ id: 9,
  titulo: "Europa Universalis IV",
  categoria: "Estrategia",
  descripcion: "Europa Universalis IV te permite controlar cualquier nación del mundo durante siglos de historia: diplomacia, comercio, guerra, colonización y estrategia global. Reescribe la historia de tu imperio.",
  img: "https://store.steampowered.com/app/236850/header.jpg",
  alt: "Europa Universalis IV",
  precio: 39.99,
  fecha_lanzamiento: new Date("8-13-2013"),
},
{ id: 10,
  titulo: "Age of Wonders 4",
  categoria: "Estrategia",
  descripcion: "Age of Wonders 4 combina estrategia 4X y combates tácticos por turnos en un mundo de fantasía. Crea tu imperio, explora, conquista y moldea el mundo con magia, diplomacia y guerra.",
  img: "https://store.steampowered.com/app/1669000/header.jpg",
  alt: "Age of Wonders 4",
  precio: 49.99,
  fecha_lanzamiento: new Date("5-02-2023"),
},
{ id: 11,
  titulo: "Dune: Spice Wars",
  categoria: "Estrategia",
  descripcion: "Dune: Spice Wars es un 4X en tiempo real ambientado en el universo de Arrakis: domina la especia, gestiona recursos, política, espionaje y conquista. Un título estratégico emergente pero muy popular.",
  img: "https://store.steampowered.com/app/1664120/header.jpg",
  alt: "Dune: Spice Wars",
  precio: 34.99,
  fecha_lanzamiento: new Date("9-14-2023"),
},
{ id: 12,
  titulo: "Hearts of Iron IV",
  categoria: "Estrategia",
  descripcion: "Hearts of Iron IV te sitúa en la Segunda Guerra Mundial: controla una nación, diseña estrategias militares, gestiona producción, espionaje, diplomacia y domina el mundo en la mayor guerra de la historia.",
  img: "https://store.steampowered.com/app/394360/header.jpg",
  alt: "Hearts of Iron IV",
  precio: 39.99,
  fecha_lanzamiento: new Date("6-6-2016"),
},

  ]

}
}

