import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';
@Component({
  selector: 'app-realidad-virtual',
  imports: [CommonModule],
  templateUrl: './realidad-virtual.html',
  styleUrl: './realidad-virtual.css',
})
export class RealidadVirtual {
  public infoVideojuegos: Videojuegos[];

  constructor() {
    this.infoVideojuegos = [
      {
        id: 1,
        titulo: "Beat Saber",
        categoria: "Realidad Virtual",
        descripcion: "Beat Saber es un juego de ritmo en VR donde empuñas dos espadas de luz para rebanar bloques al compás de la música en escenarios futuristas. Diversión accesible y altamente adictiva. ",
        img: "https://store.steampowered.com/app/620980/Beat_Saber/header.jpg",
        alt: "Beat Saber",
        precio: 29.99,
        fecha_lanzamiento: new Date("5‑21‑2019"),
      },
      {
        id: 2,
        titulo: "Half‑Life: Alyx",
        categoria: "Realidad Virtual",
        descripcion: "Half‑Life: Alyx es la entrega de la serie Half‑Life desarrollada exclusivamente para VR: una experiencia narrativa inmersiva, con interacción física, puzzles y combates contra la Combine. ",
        img: "https://store.steampowered.com/app/546560/Half_Life_Alyx/header.jpg",
        alt: "Half‑Life: Alyx",
        precio: 59.99,
        fecha_lanzamiento: new Date("3‑23‑2020"),
      },
      {
        id: 3,
        titulo: "Arizona Sunshine",
        categoria: "Realidad Virtual",
        descripcion: "Arizona Sunshine es un shooter de zombis construido exclusivamente para VR: explora un mundo apocalíptico, manipula armas con controles de movimiento y sobrevive hordas de muertos vivientes. ",
        img: "https://store.steampowered_com/app/342180/Arizona_Sunshine/header.jpg",
        alt: "Arizona Sunshine",
        precio: 19.99,
        fecha_lanzamiento: new Date("12‑06‑2016"),
      },
      {
        id: 4,
        titulo: "Boneworks",
        categoria: "Realidad Virtual",
        descripcion: "Boneworks es un sandbox de acción física en realidad virtual: cada objeto puede usarse, el entorno responde a las leyes de la física y los jugadores pueden crear sus propias herramientas o armas. ",
        img: "https://store.steampowered.com/app/823500/BONEWORKS/header.jpg",
        alt: "Boneworks",
        precio: 39.99,
        fecha_lanzamiento: new Date("12‑10‑2019"),
      },
      {
        id: 5,
        titulo: "Pavlov VR",
        categoria: "Realidad Virtual",
        descripcion: "Pavlov VR es un shooter multijugador táctico para VR que muchos comparan con Counter‑Strike en VR: varios modos, armas realistas y servidores comunitarios activos. ",
        img: "https://store.steampowered.com/app/555160/Pavlov_VR/header.jpg",
        alt: "Pavlov VR",
        precio: 24.99,
        fecha_lanzamiento: new Date("5‑27‑2017"),
      },
      {
        id: 6,
        titulo: "Superhot VR",
        categoria: "Realidad Virtual",
        descripcion: "Superhot VR es la versión VR del aclamado juego de acción: el tiempo se mueve solo cuando tú lo haces, permitiendo una experiencia única de combate estilizado en realidad virtual. ",
        img: "https://store.steampowered.com/app/1049560/Superhot_VR/header.jpg",
        alt: "Superhot VR",
        precio: 24.99,
        fecha_lanzamiento: new Date("12‑13‑2017"),
      },
      {
        id: 7,
        titulo: "The Walking Dead: Saints & Sinners",
        categoria: "Realidad Virtual",
        descripcion: "The Walking Dead: Saints & Sinners es un survival horror VR ambientado en el universo de The Walking Dead: explora Nueva Orleans inundada, enfrenta zombis, toma decisiones morales y experimenta físicas realistas. ",
        img: "https://store.steampowered.com/app/916880/The_Walking_Dead_Saints_and_Sinners/header.jpg",
        alt: "The Walking Dead: Saints & Sinners",
        precio: 39.99,
        fecha_lanzamiento: new Date("1‑23‑2020"),
      },
      {
        id: 8,
        titulo: "Stormland",
        categoria: "Realidad Virtual",
        descripcion: "Stormland es un juego de acción‑aventura en VR con un mundo abierto y verticalidad, donde exploras, completas misiones y mejoras un exo‑traje en un entorno dinámico creado para VR. ",
        img: "https://store.steampowered.com/app/400940/Stormland/header.jpg",
        alt: "Stormland",
        precio: 49.99,
        fecha_lanzamiento: new Date("10‑15‑2019"),
      },
      {
        id: 9,
        titulo: "Lone Echo",
        categoria: "Realidad Virtual",
        descripcion: "Lone Echo te situa en el espacio como un androide ayudando a una capitana humana en una estación orbital: mecánicas de propulsión, gravedad cero y exploración VR de alta calidad. ",
        img: "https://store.steampowered.com/app/505540/Lone_Echo/header.jpg",
        alt: "Lone Echo",
        precio: 59.99,
        fecha_lanzamiento: new Date("10‑20‑2017"),
      },
      {
        id: 10,
        titulo: "Elite Dangerous: Horizons (VR support)",
        categoria: "Realidad Virtual",
        descripcion: "Elite Dangerous: Horizons con soporte VR permite explorar la galaxia como comandante de naves espaciales, comerciar, combatir y aventurarte libremente en un enorme universo en realidad virtual. ",
        img: "https://store.steampowered.com/app/359320/Elite_Dangerous/header.jpg",
        alt: "Elite Dangerous: Horizons",
        precio: 49.99,
        fecha_lanzamiento: new Date("12‑16‑2014"),
      },
      {
        id: 11,
        titulo: "No Man’s Sky (VR support)",
        categoria: "Realidad Virtual",
        descripcion: "No Man’s Sky con soporte VR te permite explorar planetas generados proceduralmente, construir bases y sobrevivir en un multiverso en VR: una experiencia inmersiva de mundo abierto adaptada a realidad virtual. ",
        img: "https://store.steampowered.com/app/275850/No_Mans_Sky/header.jpg",
        alt: "No Man’s Sky (VR support)",
        precio: 49.99,
        fecha_lanzamiento: new Date("8‑12‑2016"),
      },
      {
        id: 12,
        titulo: "Blade & Sorcery",
        categoria: "Realidad Virtual",
        descripcion: "Blade & Sorcery es un sandbox de combate cuerpo a cuerpo en VR con físicas avanzadas y mod‑friendly: lanza espadas, bloquea con escudos, dispara flechas y combate de forma visceral en realidad virtual. ",
        img: "https://store.steampowered.com/app/629730/Blade_and_Sorcery/header.jpg",
        alt: "Blade & Sorcery",
        precio: 29.99,
        fecha_lanzamiento: new Date("12‑26‑2018"),
      },

    ]
  }
}
