import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';
@Component({
  selector: 'app-realidad-virtual',
  imports: [CommonModule],
  templateUrl: './realidad-virtual.html',
  styleUrl: './realidad-virtual.css',
})
export class RealidadVirtual {
  public infoVideojuegos: Videojuegos[];

  constructor() {
    this.infoVideojuegos = [
      {
        id: 1,
        titulo: "Beat Saber",
        categoria: "Realidad Virtual",
        descripcion: "Beat Saber es un juego de ritmo en VR donde empuñas dos espadas de luz para rebanar bloques al compás de la música en escenarios futuristas. Diversión accesible y altamente adictiva. ",
        img: "https://tse1.mm.bing.net/th/id/OIP.jA8Fc3fBQyOd9zIA-McNawHaEP?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "Beat Saber",
        precio: 29.99,
        fecha_lanzamiento: new Date("5-21-2019"),
      },
      {
        id: 2,
        titulo: "Half-Life: Alyx",
        categoria: "Realidad Virtual",
        descripcion: "Half-Life: Alyx es la entrega de la serie Half-Life desarrollada exclusivamente para VR: una experiencia narrativa inmersiva, con interacción física, puzzles y combates contra la Combine. ",
        img: "https://tse1.mm.bing.net/th/id/OIP.fKCo5ObxI8_fJIlMxpdEvQHaEK?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "Half-Life: Alyx",
        precio: 59.99,
        fecha_lanzamiento: new Date("3-23-2020"),
      },
      {
        id: 3,
        titulo: "Arizona Sunshine",
        categoria: "Realidad Virtual",
        descripcion: "Arizona Sunshine es un shooter de zombis construido exclusivamente para VR: explora un mundo apocalíptico, manipula armas con controles de movimiento y sobrevive hordas de muertos vivientes. ",
        img: "https://tse1.mm.bing.net/th/id/OIP.k8HdU-QfsD8MLdbw-OMy4AHaHa?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "Arizona Sunshine",
        precio: 19.99,
        fecha_lanzamiento: new Date("12-06-2016"),
      },
      {
        id: 4,
        titulo: "Boneworks",
        categoria: "Realidad Virtual",
        descripcion: "Boneworks es un sandbox de acción física en realidad virtual: cada objeto puede usarse, el entorno responde a las leyes de la física y los jugadores pueden crear sus propias herramientas o armas. ",
        img: "https://th.bing.com/th/id/R.362d8ca2252977c98288ea581ebdb1cb?rik=FuayASCzPhsMtg&pid=ImgRaw&r=0",
        alt: "Boneworks",
        precio: 39.99,
        fecha_lanzamiento: new Date("12-10-2019"),
      },
      {
        id: 5,
        titulo: "Pavlov VR",
        categoria: "Realidad Virtual",
        descripcion: "Pavlov VR es un shooter multijugador táctico para VR que muchos comparan con Counter‑Strike en VR: varios modos, armas realistas y servidores comunitarios activos. ",
        img: "https://cdn.cloudflare.steamstatic.com/steam/apps/555160/capsule_616x353.jpg?t=1621370233",
        alt: "Pavlov VR",
        precio: 24.99,
        fecha_lanzamiento: new Date("5-27-2017"),
      },
      {
        id: 6,
        titulo: "Superhot VR",
        categoria: "Realidad Virtual",
        descripcion: "Superhot VR es la versión VR del aclamado juego de acción: el tiempo se mueve solo cuando tú lo haces, permitiendo una experiencia única de combate estilizado en realidad virtual. ",
        img: "https://tse4.mm.bing.net/th/id/OIP.YRUVd4Dlq0AdwTahvsPC7QHaEK?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "Superhot VR",
        precio: 24.99,
        fecha_lanzamiento: new Date("12-13-2017"),
      },
      {
        id: 7,
        titulo: "The Walking Dead: Saints & Sinners",
        categoria: "Realidad Virtual",
        descripcion: "The Walking Dead: Saints & Sinners es un survival horror VR ambientado en el universo de The Walking Dead: explora Nueva Orleans inundada, enfrenta zombis, toma decisiones morales y experimenta físicas realistas. ",
        img: "https://tse2.mm.bing.net/th/id/OIP.lB2dL9YVhdypG9KJvhi4FQHaEQ?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "The Walking Dead: Saints & Sinners",
        precio: 39.99,
        fecha_lanzamiento: new Date("1-23-2020"),
      },
      {
        id: 8,
        titulo: "Stormland",
        categoria: "Realidad Virtual",
        descripcion: "Stormland es un juego de acción/aventura en VR con un mundo abierto y verticalidad, donde exploras, completas misiones y mejoras un exo‑traje en un entorno dinámico creado para VR. ",
        img: "https://tse3.mm.bing.net/th/id/OIP.sGerIMhC6U5NgdYo2Ll-fQHaDJ?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "Stormland",
        precio: 49.99,
        fecha_lanzamiento: new Date("10-15-2019"),
      },
      {
        id: 9,
        titulo: "Lone Echo",
        categoria: "Realidad Virtual",
        descripcion: "Lone Echo te situa en el espacio como un androide ayudando a una capitana humana en una estación orbital: mecánicas de propulsión, gravedad cero y exploración VR de alta calidad. ",
        img: "https://tse4.mm.bing.net/th/id/OIP.GqCO0NSWFcJEVpTe3-4gUAHaEK?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "Lone Echo",
        precio: 59.99,
        fecha_lanzamiento: new Date("10-20-2017"),
      },
      {
        id: 10,
        titulo: "Elite Dangerous: Horizons (VR support)",
        categoria: "Realidad Virtual",
        descripcion: "Elite Dangerous: Horizons con soporte VR permite explorar la galaxia como comandante de naves espaciales, comerciar, combatir y aventurarte libremente en un enorme universo en realidad virtual. ",
        img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/359320/header.jpg?t=1759842966",
        alt: "Elite Dangerous: Horizons",
        precio: 49.99,
        fecha_lanzamiento: new Date("12-16-2014"),
      },
      {
        id: 11,
        titulo: "No Man’s Sky (VR support)",
        categoria: "Realidad Virtual",
        descripcion: "No Man’s Sky con soporte VR te permite explorar planetas generados proceduralmente, construir bases y sobrevivir en un multiverso en VR: una experiencia inmersiva de mundo abierto adaptada a realidad virtual. ",
        img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/275850/5f39cba0164881a53f6aee01f72180f7c619c011/header.jpg?t=1762511833",
        alt: "No Man’s Sky (VR support)",
        precio: 49.99,
        fecha_lanzamiento: new Date("8-12-2016"),
      },
      {
        id: 12,
        titulo: "Blade & Sorcery",
        categoria: "Realidad Virtual",
        descripcion: "Blade & Sorcery es un sandbox de combate cuerpo a cuerpo en VR con físicas avanzadas y mod-friendly: lanza espadas, bloquea con escudos, dispara flechas y combate de forma visceral en realidad virtual. ",
        img: "https://tse3.mm.bing.net/th/id/OIP.gJREiwVJPXgisNNpZb405AHaEK?cb=ucfimgc2&rs=1&pid=ImgDetMain&o=7&rm=3",
        alt: "Blade & Sorcery",
        precio: 29.99,
        fecha_lanzamiento: new Date("12-26-2018"),
      },

    ]
  }
}
