import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-mundo-abierto',
  imports: [CommonModule],
  templateUrl: './mundo-abierto.html',
  styleUrl: './mundo-abierto.css',
})
export class MundoAbierto {
public infoVideojuegos: Videojuegos[];

constructor() {
  this.infoVideojuegos = [
    { id: 1,
  titulo: "The Witcher 3: Wild Hunt",
  categoria: "Mundo Abierto",
  descripcion: "En The Witcher 3: Wild Hunt tomas el papel de Geralt de Rivia, cazador de monstruos, y atraviesas un vasto mundo abierto lleno de bestias, intrigas, decisiones morales difíciles y paisajes magníficos que explorar sin prisa. :contentReference[oaicite:0]{index=0}",
  img: "https://store.steampowered.com/app/292030/header.jpg",
  alt: "The Witcher 3: Wild Hunt",
  precio: 39.99,
  fecha_lanzamiento: new Date("5‑18‑2015"),
},
{ id: 2,
  titulo: "Cyberpunk 2077",
  categoria: "Mundo Abierto",
  descripcion: "Cyberpunk 2077 te sumerge en Night City, una megalópolis abierta repleta de vida, misiones, personalización de personaje y libertad para explorar, luchar y moldear tu historia en un mundo distópico de futuro cercano. :contentReference[oaicite:1]{index=1}",
  img: "https://store.steampowered.com/app/1091500/header.jpg",
  alt: "Cyberpunk 2077",
  precio: 59.99,
  fecha_lanzamiento: new Date("12‑09‑2020"),
},
{ id: 3,
  titulo: "Grand Theft Auto V",
  categoria: "Mundo Abierto",
  descripcion: "Grand Theft Auto V ofrece un enorme mapa que incluye Los Santos y sus alrededores, múltiples protagonistas entre los que cambiar, misiones principales, actividades secundarias y total libertad para robar coches, volar, explorar y vivir tu versión del crimen urbano.",
  img: "https://store.steampowered.com/app/271590/header.jpg",
  alt: "Grand Theft Auto V",
  precio: 29.99,
  fecha_lanzamiento: new Date("4‑14‑2015"),
},
{ id: 4,
  titulo: "Red Dead Redemption 2",
  categoria: "Mundo Abierto",
  descripcion: "Red Dead Redemption 2 traslada la experiencia al Viejo Oeste en un mundo abierto vivo: cabalga entre montañas y llanuras, interactúa con fauna, realiza misiones, campamento y vive una epopeya de forajidos. :contentReference[oaicite:2]{index=2}",
  img: "https://store.steampowered.com/app/1174180/header.jpg",
  alt: "Red Dead Redemption 2",
  precio: 59.99,
  fecha_lanzamiento: new Date("11‑05‑2019"),
},
{ id: 5,
  titulo: "Horizon Zero Dawn Complete Edition",
  categoria: "Mundo Abierto",
  descripcion: "Horizon Zero Dawn Complete Edition combina exploración, mundo post‑apocalíptico, máquinas animales gigantes y narrativa en un vasto mundo abierto que invita a recorrerlo y descubrir sus secretos.",
  img: "https://store.steampowered.com/app/1151640/header.jpg",
  alt: "Horizon Zero Dawn Complete Edition",
  precio: 49.99,
  fecha_lanzamiento: new Date("8‑7‑2020"),
},
{ id: 6,
  titulo: "Far Cry 6",
  categoria: "Mundo Abierto",
  descripcion: "Far Cry 6 te lleva a Yara, una isla caribeña ficticia bajo régimen dictatorial, donde la exploración del mundo abierto, los combos de armas, vehículos y misiones variadas crean una experiencia abierta e intensa.",
  img: "https://store.steampowered.com/app/1203220/header.jpg",
  alt: "Far Cry 6",
  precio: 59.99,
  fecha_lanzamiento: new Date("10‑7‑2021"),
},
{ id: 7,
  titulo: "Assassin’s Creed Valhalla",
  categoria: "Mundo Abierto",
  descripcion: "Assassin’s Creed Valhalla te permite vivir como vikingo en un mundo abierto que incluye Inglaterra, Noruega y otros territorios, con incursiones, exploración, construcción de asentamiento y libertad para decidir el camino de tu clan.",
  img: "https://store.steampowered.com/app/1713220/header.jpg",
  alt: "Assassin’s Creed Valhalla",
  precio: 59.99,
  fecha_lanzamiento: new Date("11‑10‑2020"),
},
{ id: 8,
  titulo: "Ghost of Tsushima Director’s Cut",
  categoria: "Mundo Abierto",
  descripcion: "Ghost of Tsushima Director’s Cut ofrece un mundo abierto ambientado en el Japón feudal, belleza paisajística, combate samurái estilizado y libertad para recorrer la isla de Tsushima a caballo o deslizarse entre bambús.",
  img: "https://store.steampowered.com/app/1196590/header.jpg",
  alt: "Ghost of Tsushima Director’s Cut",
  precio: 49.99,
  fecha_lanzamiento: new Date("7‑17‑2023"),
},
{ id: 9,
  titulo: "Days Gone",
  categoria: "Mundo Abierto",
  descripcion: "Days Gone es un juego de mundo abierto post‑apocalíptico donde sobrevives con tu moto, exploras un mundo arrasado por hordas de infectados, completas misiones, y enfrentas tanto humanos como criaturas. :contentReference[oaicite:3]{index=3}",
  img: "https://store.steampowered.com/app/500940/header.jpg",
  alt: "Days Gone",
  precio: 29.99,
  fecha_lanzamiento: new Date("4‑18‑2023"),
},
{ id: 10,
  titulo: "The Elder Scrolls V: Skyrim Special Edition",
  categoria: "Mundo Abierto",
  descripcion: "The Elder Scrolls V: Skyrim Special Edition te permite recorrer libremente la enorme región de Skyrim, participar en aventuras, forjar armas, explorar cuevas y criaturas, ser mago, ladrón, guerrero o todo junto.",
  img: "https://store.steampowered.com/app/489830/header.jpg",
  alt: "The Elder Scrolls V: Skyrim Special Edition",
  precio: 39.99,
  fecha_lanzamiento: new Date("10‑27‑2016"),
},
{ id: 11,
  titulo: "Just Cause 4: Reloaded",
  categoria: "Mundo Abierto",
  descripcion: "Just Cause 4 Reloaded lleva la serie a un mundo abierto grande con disrupción climática, caos, vehículos, paracaídas y un sinfín de posibilidades de destrucción y exploración libre sin ataduras.",
  img: "https://store.steampowered.com/app/1040560/header.jpg",
  alt: "Just Cause 4: Reloaded",
  precio: 19.99,
  fecha_lanzamiento: new Date("12‑4‑2018"),
},
{ id: 12,
  titulo: "Watch Dogs Legion",
  categoria: "Mundo Abierto",
  descripcion: "Watch Dogs Legion te coloca en un Londres futurista abierto para explorar, reclutar ciudadanos, hackear el sistema, hacer misiones y moverte libremente por la ciudad en modo mundo abierto con variedad de opciones.",
  img: "https://store.steampowered.com/app/1415060/header.jpg",
  alt: "Watch Dogs Legion",
  precio: 49.99,
  fecha_lanzamiento: new Date("10‑29‑2020"),
},

  ]
}
}
