import { Component } from '@angular/core';
import { Videojuegos } from '../../../../models/videojuegos';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-deportes',
  imports: [CommonModule],
  templateUrl: './deportes.html',
  styleUrl: './deportes.css',
})

export class Deportes {
public infoVideojuegos: Videojuegos[];

constructor() {
this.infoVideojuegos = [
    {
    id: 1,
    titulo: "EA SPORTS FC™ 26",
    categoria: "Deportes",
    descripcion: "El Club es tuyo en EA SPORTS FC™ 26. Juega a tu manera con una experiencia de juego renovada impulsada por los comentarios de la comunidad, Desafíos en vivo de Mánager que traen historias frescas a la nueva temporada y Arquetipos inspirados en los Grandes del deporte.",
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3405690/2d96aa1b06e453cd62dae9029d412f19e61932c3/header.jpg?t=1761904811",
    alt: "EA SPORTS FC™ 26",
    precio: 69.99,
    fecha_lanzamiento: new Date("9-25-2025"),
    },

    {
    id: 2,
    titulo: "Football Manager 26",
    categoria: "Deportes",
    descripcion: "Toma las riendas del banquillo y vive el futuro de la gestión futbolística.",
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3551340/7d28b9aa8dcfcd96593d112736f58b4b1d3cc7a4/header.jpg?t=1762339168",
    alt: "Football Manager 26",
    precio: 49.99,
    fecha_lanzamiento: new Date("11-4-2025"),
    },

    {
    id: 3,
    titulo: "NBA 2K26",
    categoria: "Deportes",
    descripcion: "El derecho a presumir está en juego en Mi CARRERA, MyTEAM, Mi NBA, La W y Jugar ya. Exhibe tu colección de movimientos con hiperrealismo, gracias a la tecnología ProPLAY™, y desafía a tus amigos, o rivales, en los modos competitivos de NBA 2K26, y leave no doubt: tú eres el rey.",
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3472040/c3c09a28c455c275d05e6b8c763ff78626f7cdaf/header_alt_assets_0.jpg?t=1761580807",
    alt: "NBA 2K26",
    precio: 79.99,
    fecha_lanzamiento: new Date("9-5-2025"),
    },

    {
    id: 4,
    titulo: "WWE 2K25",
    categoria: "Deportes",
    descripcion: "Celebra The Bloodline en Showcase. Compite online en Mi GM. ¡El juego ampliado incluye lucha intergénero, lucha en cadena, saltos de barrera, el regreso de las Promociones y mucho más!",
    img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2878960/header.jpg?t=1761227335",
    alt: "WWE 2K25",
    precio: 59.99,
    fecha_lanzamiento: new Date("3-13-2025"),
    },

    { id: 5,
  titulo: "Undisputed",
  categoria: "Deportes",
  descripcion: "Undisputed es un juego auténtico de boxeo que te pone en el ring con los mejores luchadores del mundo. Con mecánicas profundas de defensa, ataque, footwork y control total del combate, podrás vivir el camino desde el torneo amateur hasta convertirte en campeón indiscutido. ",
  img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1451190/header.jpg?t=1761667556",
  alt: "Undisputed",
  precio: 39.99,
  fecha_lanzamiento: new Date("10-08-2024"),
},
{ id: 6,
  titulo: "skate.",
  categoria: "Deportes",
  descripcion: "Skate. reimagina el skateboarding en un mundo abierto donde expresarte sobre la tabla, crear tus propias rampas, trucos y vivir la escena urbana en línea. Vive la libertad del patín en una ciudad para todos.",
  img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/3354750/79c5a87b61a396cc6e6b69e3a083727f175dea83/header.jpg?t=1761670816",
  alt: "skate.",
  precio: 12.99,
  fecha_lanzamiento: new Date("09-16-2025"),
},
{ id: 7,
  titulo: "Golf With Your Friends",
  categoria: "Deportes",
  descripcion: "Golf With Your Friends te invita a competir en minigolf frenético con hasta 12 jugadores, en campos disparatados, power-ups, modos creativos y un editor de niveles para llevar la diversión con amigos al siguiente nivel.",
  img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/431240/header.jpg?t=1761835073",
  alt: "Golf With Your Friends",
  precio: 14.99,
  fecha_lanzamiento: new Date("05-19-2020"),
},
{ id: 8,
  titulo: "Session: Skate Sim",
  categoria: "Deportes",
  descripcion: "Session: Skate Sim es una experiencia hiperrealista de skate donde cada stick representa uno de los pies. Patina en spots icónicos, personaliza tu skater, graba tus líneas y sumérgete en la cultura del skate sin sistema de puntuación: solo tú y la tabla.",
  img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/861650/ac22f7a4d6a6dac8a67a0a3882554ca7452440b2/header_alt_assets_7_spanish.jpg?t=1761925415",
  alt: "Session: Skate Sim",
  precio: 39.99,
  fecha_lanzamiento: new Date("09-22-2022"),
},
{ id: 9,
  titulo: "REMATCH",
  categoria: "Deportes",
  descripcion: "REMATCH es un juego de fútbol arcade 5 vs 5 en tercera persona donde tu habilidad decide, no las estadísticas. Juega en equipo, pasa, marca, vive el juego rápido y sin faltas que frenen la acción.",
  img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2138720/header.jpg?t=1761052542",
  alt: "REMATCH",
  precio: 29.99,
  fecha_lanzamiento: new Date("06-19-2025"),
},
{ id: 10,
  titulo: "Riders Republic",
  categoria: "Deportes",
  descripcion: "Riders Republic te sumerge en un enorme mundo multijugador de deportes extremos: bici, esquí, snowboard, wingsuit y más. Corre, vuela, compite con decenas de jugadores simultáneos en pistas abiertas llenas de acción.",
  img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2290180/2eb6256ba124d79e77b005e29293671acb77e504/header.jpg?t=1760115205",
  alt: "Riders Republic",
  precio: 39.99,
  fecha_lanzamiento: new Date("06-08-2023"),
},
{ id: 11,
  titulo: "PGA TOUR 2K25",
  categoria: "Deportes",
  descripcion: "PGA TOUR 2K25 es la simulación de golf más completa: tres Majors, personalización profunda, editor de campos y juego online cross-plataforma. Swing perfecto, estilo propio y llega al campo para ganar.",
  img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2385530/header.jpg?t=1761750361",
  alt: "PGA TOUR 2K25",
  precio: 69.99,
  fecha_lanzamiento: new Date("02-27-2025"),
},
{ id: 12,
  titulo: "MX vs ATV Legends",
  categoria: "Deportes",
  descripcion: "MX vs ATV Legends ofrece carreras todoterreno con motos, quads y UTV en entornos abiertos, modo carrera, online y físicas refinadas para dominar los caminos agrestes y convertirte en leyenda off-road.",
  img: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1205970/header.jpg?t=1756368595",
  alt: "MX vs ATV Legends",
  precio: 59.99,
  fecha_lanzamiento: new Date("06-28-2022"),
},

  ]

}
}

